import Head from "next/head";
import { Decimal } from "@prisma/client/runtime";
import { GetServerSideProps } from "next";
import Tickets, { TicketsProps } from "../components/Tickets";
import Input from "../components/Input"
import IInput from "../interfaces/IInput";
import { useState } from "react";

type Props = {
  feed: TicketsProps[]
}

const Home: React.FC<Props> = props => {
  const [inputData, setInputData] = useState<IInput>()


  function setData(id: number,
    evento: string,
    artista: string,
    local: string,
    descricao: string,
    data: string,
    preco: Decimal,
    url: string) {

    setInputData({
      id: id,
      evento: evento,
      descricao: descricao,
      url: url,
      artista: artista,
      data: data,
      local: local,
      preco: preco.toString()
    })
  }

  return (
    <div>
      <Head>
        <title>crud tickets</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Input {...inputData} />
      <main style={{display: "flex", flexDirection: "row", justifyContent: "space-evenly", flexWrap: "wrap"}}>
        {props.feed.map(tickets => (
          <div key={tickets.id}>
            <Tickets tickets={{
              id: tickets.id,
              evento: tickets.evento,
              artista: tickets.artista,
              local: tickets.local,
              descricao: tickets.descricao,
              data: tickets.data,
              preco: tickets.preco,
              url: tickets.url,
              setData: (id: number,
                evento: string,
                artista: string,
                local: string,
                descricao: string,
                data: string,
                preco: Decimal,
                url: string) => setData(id, evento, artista, local, descricao, data, preco, url)
            }} />
          </div>
        ))}
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/tickets/find")
  const feed = await res.json()
  return {
    props: { feed },
  }
}

export default Home